In [1]:
import pandas as pd
df_churn =  pd.read_csv("dataset.csv")
df_churn.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [2]:
df_churn.columns
df_churn.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [3]:
#Retirando espaços antes e depois da str e alterando vazios para null
df_churn["TotalCharges"] = (df_churn["TotalCharges"].str.strip()
                            .replace('', pd.NA))

In [4]:
# Convertendo de str para float
df_churn["TotalCharges"].astype(float)

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: TotalCharges, Length: 7043, dtype: float64

In [5]:
# Conferindo quais colunas tem null e alterando de null para 0 na coluna Total Charges
df_churn.isnull().sum()
df_churn["TotalCharges"] = df_churn["TotalCharges"].fillna(0)

In [6]:
# Alterei dados de sim e não para número, assim podendo calcular média
convert_calc = ["Partner", "Dependents", "Churn"]

df_churn[convert_calc] = df_churn[convert_calc].replace({"Yes": 1, "No": 0})
df_churn[convert_calc] = df_churn[convert_calc].astype(int)
df_churn.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   int64
 4   Dependents        7043 non-null   int64
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   int64
dtypes: float64(1), int64(5), object(1), str(14)
memory usage: 1.1+ MB

In [7]:
# Os 5 cliente que mais pagam mensalmente
df_churn = df_churn.sort_values(by=["MonthlyCharges"], ascending= False)
df_churn.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
4586,7569-NMZYQ,Female,0,1,1,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),118.75,8672.45,0
2115,8984-HPEMB,Female,0,0,0,71,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,118.65,8477.6,0
3894,5989-AXPUC,Female,0,1,0,68,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Mailed check,118.60,7990.05,0
4804,5734-EJKXG,Female,0,0,0,61,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Electronic check,118.60,7365.7,0
5127,8199-ZLLSA,Male,0,0,0,67,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Bank transfer (automatic),118.35,7804.15,1

In [11]:
#Verificação de valores duplicados

df_churn.duplicated().sum()
df_churn.duplicated(subset=["customerID"]).sum()

np.int64(0)

In [12]:
df_churn.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
4586,7569-NMZYQ,Female,0,1,1,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),118.75,8672.45,0
2115,8984-HPEMB,Female,0,0,0,71,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,118.65,8477.6,0
3894,5989-AXPUC,Female,0,1,0,68,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Mailed check,118.60,7990.05,0
4804,5734-EJKXG,Female,0,0,0,61,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Electronic check,118.60,7365.7,0
5127,8199-ZLLSA,Male,0,0,0,67,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Bank transfer (automatic),118.35,7804.15,1

In [ ]:
#Criando a tabela dim_cliente

dim_clientes = df_churn[["customerID","gender","SeniorCitizen","Partner", "Dependents"]] 

dim_clientes.head()

      customerID  gender  SeniorCitizen  Partner  Dependents
4586  7569-NMZYQ  Female              0        1           1
2115  8984-HPEMB  Female              0        0           0
3894  5989-AXPUC  Female              0        1           0
4804  5734-EJKXG  Female              0        0           0
5127  8199-ZLLSA    Male              0        0           0

In [17]:
#Criando a tabela dim_servicos

dim_servicos = df_churn[["customerID", "PhoneService", "MultipleLines", "InternetService", "OnlineSecurity", "DeviceProtection", "TechSupport", "OnlineBackup", "StreamingTV", "StreamingMovies"]]

dim_servicos.head()

,customerID,PhoneService,MultipleLines,InternetService,OnlineSecurity,DeviceProtection,TechSupport,OnlineBackup,StreamingTV,StreamingMovies
4586,7569-NMZYQ,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes
2115,8984-HPEMB,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes
3894,5989-AXPUC,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes
4804,5734-EJKXG,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes
5127,8199-ZLLSA,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes

In [18]:
#Construindo a tabela dim_contrato

dim_contrato = df_churn[["customerID" ,"Contract", "PaperlessBilling","PaymentMethod"]]

dim_contrato.head()

      customerID  Contract PaperlessBilling              PaymentMethod
4586  7569-NMZYQ  Two year              Yes  Bank transfer (automatic)
2115  8984-HPEMB  Two year              Yes           Electronic check
3894  5989-AXPUC  Two year               No               Mailed check
4804  5734-EJKXG  One year              Yes           Electronic check
5127  8199-ZLLSA  One year              Yes  Bank transfer (automatic)

In [21]:
#criando a coluna fato

fato_churn = df_churn[["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]]

fato_churn.head()

      customerID  tenure  MonthlyCharges TotalCharges  Churn
4586  7569-NMZYQ      72          118.75      8672.45      0
2115  8984-HPEMB      71          118.65       8477.6      0
3894  5989-AXPUC      68          118.60      7990.05      0
4804  5734-EJKXG      61          118.60       7365.7      0
5127  8199-ZLLSA      67          118.35      7804.15      1

In [23]:
#exportando tabelas como csv

dim_clientes.to_csv("dim_clientes.csv", index=False)
dim_servicos.to_csv("dim_servicos.csv", index=False)
dim_contrato.to_csv("dim_contrato.csv", index=False)
fato_churn.to_csv("fato_churn.csv", index=False)